backend:
  name: github
  repo: pickyzz/blog-rebuild # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to main)

local_backend: true

publish_mode: editorial_workflow

media_folder: "public/assets/images/blog" # Folder where user uploaded files should go
public_folder: "/assets/images/blog"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "blog" # Used in the UI, ie.: "New Post"
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    format: frontmatter
    fields: # The fields each document in this collection have
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "postSlug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "pubDatetime", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Feathured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "ogImage", name: "ogImage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["other"] }
