name: Build and deploy
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
        name: "Checkout Source Code"
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: "Setup Bun Runtime"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: "create env file"
        env:
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
        shell: bash
        run: |
          touch .env
          echo "DATABASE_ID=$DATABASE_ID" >> .env
          echo "NOTION_KEY=$NOTION_KEY" >> .env

      - name: "Install dependencies"
        run: bun install

      - name: "Build output"
        run: |
          bun run generate

      - name: "Publish to Cloudflare Pages"
        uses: pickyzz/cf-pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pickyzz-blog
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          logsOnFailure: true
