name: Build and deploy
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
        name: "Checkout Source Code"
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: "Setup Bun Runtime"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: "Setup jampack cache"
        uses: actions/cache@v4
        id: jampack
        with:
          path: .jampack
          key: jampack-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            jampack

      - name: "create env file"
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_DATABASE_ID: ${{ secrets.DATABASE_ID }}
          ENV_NOTION_KEY: ${{ secrets.NOTION_KEY }}

      - name: "Install dependencies"
        run: bun install

      - name: "Build output"
        run: |
          bun run sync:published
          bun run generate

      - name: "Publish to Cloudflare Pages"
        uses: pickyzz/cf-pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pickyzz-blog
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          logsOnFailure: true
