name: Netlify Builds
on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout Source Code'

      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: 'Get pnpm store directory'
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 'Setup pnpm cache'
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nodeModules-
            ${{ runner.os }}-pnpm-store-

      - name: 'Install dependencies'
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm i --shamefully-hoist --prefer-offline
        env:
          CI: true

      - name: 'Build Development'
        run: pnpm build

      - name: 'Deploy to Netlify'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GH_TOKEN }}
          deploy-message: '${{ github.event.head_commit.message }}'
          enable-pull-request-comment: true
          overwrites-pull-request-comment: true
          enable-commit-comment: true
          enable-commit-status: true
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
