name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: "Setup Bun Runtime"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: "Install dependencies"
        run: bun install --yarn

      - name: "Run linter"
        run: |
          bun run lint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: bun run test

      - name: "upload artifacts"
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          path: |
            bun.lockb
            yarn.lock
          retention-days: 30