name: Test
on:
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: "Setup Bun Runtime"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: "create env file"
        env:
          DATABASE_ID: ${{ secrets.DATABASE_ID_TEST }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
        shell: bash
        run: |
          touch .env
          echo "DATABASE_ID=$DATABASE_ID" >> .env
          echo "NOTION_KEY=$NOTION_KEY" >> .env

      - name: "Install dependencies"
        run: bun install

      - name: "Run linter"
        run: |
          bun run lint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          bun run sync:published
          bun run test

  automerge:
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto-merge pull request
        run: gh pr merge "$PR_URL" --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
