name: post update check

on:
  schedule:
    - cron: "0 * * * *" #every hour
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: "Setup Bun Runtime"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: "create env file"
        env:
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
        shell: bash
        run: |
          touch .env
          echo "DATABASE_ID=$DATABASE_ID" >> .env
          echo "NOTION_KEY=$NOTION_KEY" >> .env

      - name: check for post update
        run: |
          bun install
          bun run sync:logs

      - name: commit
        run: |
          git config --global user.name 'potbick'
          git config --global user.email 'potbick@users.noreply.github.com'
          git add --all
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated with new content" && git push -u origin ${{ github.ref_name }} || echo "No changes to commit"
